### ISSUE TITLE
typo in readme

### ISSUE THREAD

**Issue by zeronumbers** [pappijx/Vite-react-eslint-prettier-husky-setup#1]
written: it it
should be: it is

exact line:
-> We need prettier to format our code properly so that it it more readable and so everyone use similar code formatting

**Comment by zeronumbers** [comment]
Instruction to install eslint-config-airbnb-typescript is wrong.
in package.json I can see that it is installed as dev dependency, however when command from readme is executed it will install as dependency because you forgot --save-dev

exact line:
terminal> npm install eslint-config-airbnb-typescript
should be:
terminal> npm install --save-dev eslint-config-airbnb-typescript

**Comment by timotheeMM** [comment]
PR #2
