### ISSUE TITLE
Error running  `npm run lint .`

### ISSUE THREAD

**Issue by albertcito** [pappijx/Vite-react-eslint-prettier-husky-setup#3]
I added this value to script `"lint": "eslint"` to `package.json`

I ran `npm run lint . --fix` it display this error:

> Vite-react-eslint-prettier-husky-setup/vite.config.ts
  0:0  error  Parsing error: ESLint was configured to run on `<tsconfigRootDir>/vite.config.ts` using `parserOptions.project`: /users/albert/documents/albert/vite-react-eslint-prettier-husky-setup/tsconfig.json
However, that TSConfig does not include this file. Either:
> - Change ESLint's list of included files to not include this file
> - Change that TSConfig to include this file
> - Create a new TSConfig that includes this file and include it in your parserOptions.project
See the typescript-eslint docs for more info: https://typescript-eslint.io/linting/troubleshooting#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file

**Comment by ayushpapnai** [comment]
I will check this and let you know.

Thank you for pointing it out.

**Comment by ayushpapnai** [comment]
I have checked this and it works fine for me
